apiVersion: v1
kind: Service
metadata:
  name: cicd-web
  namespace: cicd-web
spec:
  type: ClusterIP
  selector:
    app: cicd-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP